apiVersion: batch/v1
kind: Job
metadata:
  name: oneview-prepare-bm4-assets
  namespace: open-cluster-management
spec:
  selector:
    matchLabels:
      app: oneview-prepare-bm4-assets
  template:
    metadata:
      app: oneview-prepare-bm4-assets
    spec:
      containers:
        - name: job
          image: quay.io/fdavalo/oneview-2-acm-assets:latest
          command:
            - python3
            - bm4.py
          env:
            - name: ONEVIEWSDK_IP
              value: oneview.redhat.hpecic.net
            - name: ONEVIEWSDK_USERNAME
              valueFrom:
                secretKeyRef:
                  name: oneview
                  key: username
            - name: ONEVIEWSDK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oneview
                  key: password
      restartPolicy: Never
