apiVersion: v1
kind: Secret
metadata:
  name: baremetal-asset-secret-@name@
  namespace: @namespace@
type: Opaque
data:
  password: @password64@
  username: @username64@
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: @name@
  namespace: @namespace@
  annotations:
    inspect.metal3.io: disabled
  labels:
    infraenvs.agent-install.openshift.io: "@namespace@"
spec:
  bootMode: "UEFI"
  bmc:
    address: @url@
    disableCertificateVerification: true
    credentialsName: baremetal-asset-secret-@name@
  bootMACAddress: @mac@
  online: true
